### ISSUE TITLE
The save action "Convert to enhanced 'for' loops" may generate compilation problems

### ISSUE THREAD

**Issue by fedejeanne** [vi-eclipse/Eclipse-JDT#11]
Reported by Peter K.

## The problem
The _Save action_ called **Convert to enhanced 'for' loops** (under _Preferences > Save actions > Java Features_) generates compilation problems sometimes.

In this piece of code in the method `DeltaMigrationEntry::handleFileErrors`, the iterator is also passed as a parameter to other methods but the replacement happens anyway.

### Code before the replacement
```java
      Iterator<Integer> intIterator = ...;
      while (intIterator.hasNext()) {
        Integer attributeInstance = intIterator.next();
        ...
        if (someCondition) {
          ...
          if (!Objects.equals(oldLength, newLength)) {
            // the iterator is needed here
            someMethod(10, resource, intIterator, null, oldLength, newLength);
            ...
          }
        …
      }
```

### Code after the replacement
```java
      for (Integer someInt : ...) {
        ...
        if (someCondition) {
          ...
          if (!Objects.equals(oldLength, newLength)) {
            // intIterator is still needed here --> COMPILATION ERROR!
            someMethod(10, resource, intIterator, null, oldLength, newLength);
            ...
          }
        …
      }
```

## TODOs for Ready
**Try to reproduce the error**. This has been tested in 2023-06 and the problem is **not** reproducible but this might be because the code can't even be compiled.

**Comment by fedejeanne** [comment]
The problem is not reproducible in `2023-06`

**Comment by HeikoKlare** [comment]
The issue still exists for other use case, as documented in #14.
