### ISSUE TITLE
Run Configurations Dialog: BinaryTypeBinding.superInterfaces() Takes Too Long

### ISSUE THREAD

**Issue by fedejeanne** [vi-eclipse/Eclipse-JDT#16]
_(see https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1214)_

When opening the dialog "Run configurations...", this method takes up an important slice of the total time.

![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/2205684/6773c5dd-6075-4fa6-9088-c424197140f4)

See related issue for a CPU snapshot (*.nps).

Pre-requisite: 
1. Need to have Junit5.
2. Need to have a test run configuration.
3. Test Class should have a parent class.

**Comment by ShahzaibIbrahim** [comment]
Unable to reproduce issue without a big workspace such as PPT.

**Comment by fedejeanne** [comment]
This issue needs to be addressed in a broader scope: JDT is very complex and we need to come up with a better strategy to address several performance problems
