### ISSUE TITLE
Performance Problems When Opening the Context Menu "Run As..."

### ISSUE THREAD

**Issue by fedejeanne** [vi-eclipse/Eclipse-JDT#17]
It takes about 20 seconds to open the _Run As..._ context menu when using it in some specific classes. 

Sample: [slowDebugAs.zip](https://github.com/vi-eclipse/Eclipse-JDT/files/13267340/slowDebugAs.zip)

![Image](https://github.com/vi-eclipse/Eclipse-JDT/assets/2205684/8b39119e-5aa7-4a95-b225-7a29cc0b280c)

## Tasks
* [x] #20
* [x] #19

## Workaround
* [x] https://github.com/eclipse-platform/eclipse.platform/pull/1005 (reverted in https://github.com/eclipse-platform/eclipse.platform.ui/pull/1679)

**Comment by fedejeanne** [comment]
@ShahzaibIbrahim I've split the tasks in 2: one for PPT and one for JDT. We can talk tomorrow about how to go about the tasks for JDT and eventually add some more or refine the ones I described.

I'll take care of the tasks that are specific to PPT.

**Comment by HeikoKlare** [comment]
This issue seems to be "in progress". Could please assign according labels and move it to the proper stage in the backlog board?

**Comment by fedejeanne** [comment]
@ShahzaibIbrahim I moved the JDT tasks to #19 and I assigned the issue to you

**Comment by HeikoKlare** [comment]
What is the current state of this?

**Comment by fedejeanne** [comment]
I added the "Workaround", which got reverted. From my point of view there is't much more we can do

**Comment by fedejeanne** [comment]
Withdrawn
