### ISSUE TITLE
Add caching to the "Run As..." context menu

### ISSUE THREAD

**Issue by fedejeanne** [vi-eclipse/Eclipse-JDT#19]
_(Moved from #17)_

Analyze (and, if necessary, improve) in JDT

* What happens if someone uses the same _&lt;enablement&gt;_ (in `plugin.xml`) more than once?
* Is it possible/meaningful to cache some evaluations?
* Is it possible to tune the call to `ASTParser::createAST` so that only the necessary data for `org.eclipse.jdt.internal.junit.launcher.JUnit5TestFinder.isTest(ITypeBinding)` is extracted?

**Comment by ShahzaibIbrahim** [comment]
After analyzing, Here are my answers. 
 
> * What happens if someone uses the same _<enablement>_ (in `plugin.xml`) more than once?

The enablement expression will be evaluated again but the caching for individual expression is already done so the time for next enablementExpression will be significantly lower. We can also analyze how caching is working by setting the `org.eclipse.core.expressions/tracePropertyResolving` property to "true" in .options file in org.eclipse.core.expressions package. 

> * Is it possible/meaningful to cache some evaluations?

As mentioned above, caching is already happening at lower level and it makes more sense to have caching there for each expression rather than combination of expression. 

> * Is it possible to tune the call to `ASTParser::createAST` so that only the necessary data for `org.eclipse.jdt.internal.junit.launcher.JUnit5TestFinder.isTest(ITypeBinding)` is extracted?

Not sure about that.

**Comment by fedejeanne** [comment]
Thank you for documenting your findings!

> > * Is it possible to tune the call to `ASTParser::createAST` so that only the necessary data for `org.eclipse.jdt.internal.junit.launcher.JUnit5TestFinder.isTest(ITypeBinding)` is extracted?
> 
> Not sure about that.

We should look into that too since it might speed up the whole thing. Specifically, I was thinking of maybe adding some new `bits` that the `ASTParser` can pass to the method `CompilationUnitResolver::resolve` (as a parameter [here](https://github.com/eclipse-jdt/eclipse.jdt.core/blob/master/org.eclipse.jdt.core/dom/org/eclipse/jdt/core/dom/ASTParser.java#L1252C10-L1252C15)) so that the resolver skips unnecessary calls like `CompilationUnitScope::faultInTypes` (this is an assumption, I haven't checked if that call is actually needed).

![Image](https://github.com/vi-eclipse/Eclipse-JDT/assets/2205684/8b39119e-5aa7-4a95-b225-7a29cc0b280c)

Could you please check that, @ShahzaibIbrahim ?

**Comment by ShahzaibIbrahim** [comment]
> Could you please check that, @ShahzaibIbrahim ?

before I could try adding bits and control the execution of faultInTypes method, I tried shutting that of manually with if(false) and realized that Run as.. is not showing Junit Test option on sub menu, that means there is something that faultInTypes method evaluate and our jUnit5Tester class uses to evaluate the pre condition to check whether to show it or not.. In short, this needs to be executed and thus its not called unnecessarily.

**Comment by fedejeanne** [comment]
No meaningful optimizations/changes were introduced.
