### ISSUE TITLE
Move the "Filters" button in Call Hierarchy view to the top level bar

### ISSUE THREAD

**Issue by fedejeanne** [vi-eclipse/Eclipse-JDT#26]
# Current status
The _Filters_ button is currently somewhat hidden in the "View menu" (three dots) of the bar:
![360338888-871b0563-a00e-474a-acb9-0bdcdbd268a6](https://github.com/user-attachments/assets/3ba25b6e-6f74-419c-b60b-58dd36990625)

# Goal
Move it to the top level bar so it becomes more visible, just like other views do:

![360339389-7e444d34-0c6c-48e7-bb69-b1624d83826b](https://github.com/user-attachments/assets/c653dedd-aed7-456f-89ab-114868d3cb82)

![360339855-55019640-291d-45e4-9027-5948dc01a75b](https://github.com/user-attachments/assets/0bd202bd-438e-4bf5-9c6e-27cd5d2e3f87)

![360340425-ed35f8b3-bc07-4f24-90cc-9fccc8e1bc62](https://github.com/user-attachments/assets/8dac9c0f-aa3f-4edd-ab11-4b7481164ce4)

**Comment by jannisCode** [comment]
https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/1671
