### ISSUE TITLE
Show only tests in the "Call Hierarchy" view

### ISSUE THREAD

**Issue by fedejeanne** [vi-eclipse/Eclipse-JDT#27]
## Current status
In the _Call Hierarchy_ view one can filter out the calls to a method coming from _test code_.

![Image](https://github.com/user-attachments/assets/eb21974b-3836-4fc1-8c26-ed807bb21f5e)

![Image](https://github.com/user-attachments/assets/a84eb1fe-0233-4a0b-bee8-2b0a38a97775)

This means that the view will show all calls **except** the ones coming from test methods

## Goal
It should be possible to do the exact opposite too _i.e._ show **only** the calls coming from test methods.

## Proposal
Replace the option `Filter Test Code` with 3 options (**radio** buttons):
* `Show All` (default option)
* `Hide Test Code` 
* `Show Test Code only`

**Comment by jannisCode** [comment]
https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/1687
