### ISSUE TITLE
Navigation/Changes in Large Java Classes with Large Inheritance Hierarchies Sometimes Very Slow

### ISSUE THREAD

**Issue by HeikoKlare** [vi-eclipse/Eclipse-JDT#5]
### Current Behavior

In large Java classes (thousands of lines) with large inheritance hierarchies (hundreds to thousands of classes), the navigation within the Java editor or changes within the editor become very slow (meaning freezes for minutes). Although this situation may or should not or seldom occur in handwritten code, it may occur (and does in our case) with generated source code.
One identified reason is that the "mark occurrences" background job updates the annotation model rather inefficiently. 

### Expected Behavior

The Java code editor should still be responsive with large source code files for classes in large inheritance hierarchies.

The issue is documented in more detail in the Eclipse JDT UI repository: https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/665

There is a related but still different issue in Platform UI: https://github.com/eclipse-platform/eclipse.platform.ui/issues/861

**Comment by jonahgraham** [comment]
@HeikoKlare - do you have any prelim work on this I can look at to see if I can progress the platform ui related issue?

**Comment by HeikoKlare** [comment]
@jonahgraham Sorry for taking so long to reply. See my comment on the Platform UI issue: https://github.com/eclipse-platform/eclipse.platform.ui/issues/861#issuecomment-1629410298

**Comment by HeikoKlare** [comment]
PR: https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/677
